name: Flutter CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Instalar dependências
        run: flutter pub get

      - name: Analisar código
        run: flutter analyze

      - name: Verificar formatação
        run: dart format --output=none --set-exit-if-changed lib