name: Flutter CD

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Instalar dependências
        run: flutter pub get

      - name: Gerar APK
        run: flutter build apk --release

      - name: Salvar APK como artefato
        uses: actions/upload-artifact@v4
        with:
          name: listinha-apk
          path: build/app/outputs/flutter-apk/app-release.apk